version: '3.9'

services:
  backend:
    build: .
    container_name: robotics-bot-backend
    restart: unless-stopped
    stdin_open: true
    tty: true
    working_dir: /home/ws
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/home/ws
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/robotics_club
    depends_on:
      - db
    ports:
      - "8000:8000"

  terminal:
    build: .
    stdin_open: true
    tty: true
    working_dir: /home/ws
    command: []
    volumes:
      - .:/home/ws

  db:
    image: postgres:14
    container_name: robotics-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: robotics_club
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
