services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./databases/postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  admin_service:
    build: ./admin_service
    container_name: admin_service
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./admin_service:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

