# Generated by Django 5.2.5 on 2025-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('telegram_alias', models.CharField(blank=True, max_length=255)),
                ('access_level', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], max_length=10)),
                ('about', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='users_equipment', to='equipment.equipment')),
            ],
        ),
    ]
