# Generated by Django 5.2.5 on 2025-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('place', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], max_length=20)),
                ('guests', models.ManyToManyField(blank=True, related_name='guest_events', to='people.person')),
                ('speakers', models.ManyToManyField(blank=True, related_name='speaking_events', to='people.person')),
                ('visits', models.ManyToManyField(blank=True, related_name='visited_events', to='people.person')),
            ],
        ),
    ]
